version: "2.1"

services:

  postgres:
    image: postgres:9.4-alpine
    volumes: ["postgres-data:/var/lib/postgresql/data"]
    networks: [backing-services]
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 1s
      retries: 35

  app:
    image: 127.0.0.1:5000/app
    build:
      context: ..
      dockerfile: ./docker-compose/kotlin-postgres-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes: ["app-data:/home/app"]
    networks: [backing-services]
    ports: ["8080:8080"]
    environment:
      DB_HOST: postgres
    mem_limit: 1g

volumes:
  postgres-data: {}
  app-data: {}

networks:
  backing-services:
    driver: bridge
